repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.11.0
  #   hooks:
  #     - id: markdownlint
  #       language: docker_image
  #       files: \.(md|mdown|markdown)$
  #       entry: markdownlint/markdownlint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.5.0
    hooks:
      - id: hadolint-docker
        files: (Dockerfile|DOCKERFILE|Dockerfile.test)$
