version: "3.3"

services:
  app:
    image: sgmakarov/devops:latest
    build:
      context: app_python
    container_name: application
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.application.entrypoints=websecure"
      - "traefik.http.routers.application.tls.certresolver=letsencrypt"
      - "traefik.http.services.application.loadbalancer.server.port=5000"
    ports:
      - 5000:5000
