apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.app.name }}
    spec:

      containers:
        - image: {{ .Values.app.image }}
          name: {{ .Values.app.name }}
          ports:
            - name: yolocat
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          securityContext:
            capabilities:
              add: [SYS_TIME]
{{- if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
{{- end -}}
