Vagrant.require_version ">= 1.8.0"
Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox" do |v|
        v.gui = true
        v.memory = 4096
        v.cpus = 2
    end
  config.vm.box = "generic/debian10"
  config.vm.network "forwarded_port", guest: 80, host: 1234

  # we will need this for later, when will test our playbooks
  # config.vm.provision "ansible" do |ansible|
  #   ansible.verbose = "v"
  #   ansible.playbook = "../ansible/app.yml"
  # end
end
