plugin: google.cloud.gcp_compute
projects:
  - "diesel-ellipse-309714"
service_account_file: /tmp/ansible-gce-keyfile.json
auth_kind: serviceaccount
# exclude k8s nodes
filters:
 - name !=  gke-k8s-*
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  - key: labels
    prefix: label
  - key: zone
    prefix: zone

compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
