
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["victoriametrics:8428"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
