Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|

  config.vm.define "docker_vagrant"
  config.vm.box = "generic/debian10"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "docker.yml"
    ansible.groups = {
        "label_service_app" => ["docker_vagrant"],
      }
  end
end
