---
- hosts: label_service_application
  name: "Run docker-compose on a docker VM"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  post_tasks:
    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        mode: 0755

    - name: "Copy app compose file"
      copy:
        src: docker-compose.app.yml
        dest: /opt/app/docker-compose.yml

    - name: "Run app"
      community.docker.docker_compose:
        project_src: /opt/app/
        files: docker-compose.yml
