version: "3.3"

services:
  proxy:
    image: sgmakarov/devops:latest
    container_name: application
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.application.entrypoints=websecure"
      - "traefik.http.routers.application.tls.certresolver=letsencrypt"
      - "traefik.http.services.application.loadbalancer.server.port=5000"
    networks:
      - web

networks:
  web:
    external: true
