{{- if .Values.imageCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
---
{{- if .Values.app.env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-environment
type: kubernetes.io/opaque
data:
  password: {{ .Values.app.env.password | b64enc | quote }}
{{- end -}}
