apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  serviceName: {{ .Values.app.name }}
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.app.name }}
    spec:
      containers:
        - image: {{ .Values.app.image }}
          name: {{ .Values.app.name }}
          ports:
            - name: yolocat
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          securityContext:
            capabilities:
              add: [SYS_TIME]
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
            - name: DATA_DIR
              value: {{ .Values.app.datadir }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-environment
                  key: password
          volumeMounts:
            - name: {{ .Values.app.name }}-config-mount
              mountPath: /app/config.json
              subPath: config.json
          volumeMounts:
            - name: {{ .Values.app.name }}-visited-mount
              mountPath: {{ .Values.app.datadir }} 
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.app.name }}-visited-mount
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

{{- if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
{{- end -}}
