name: Test, build and push app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./app_python/
          file: ./app_python/Dockerfile.test
          load: true
          tags: "test:latest"
      - name: Run tests
        run: |
          docker run "test"
  docker:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            sgmakarov/devops
          tags: |
            type=sha
            type=ref,event=tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./app_python/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
