name: Test, build and push app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build test image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: app_python/
          file: Dockerfile.test
          tags: test:${GITHUB_SHA}
      -
        name: Run tests
        run: |
          docker run test:${GITHUB_SHA}
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: app_python/
          tags: sgmakarov/devops:${GITHUB_SHA},sgmakarov/devops:latest
